name: Daily Aparat Bot

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install packages
        run: pip install moviepy pillow gtts requests

      - name: Generate Video
        run: python generate_video.py

      - name: Upload to Aparat
        env:
          APARAT_USERNAME: ${{ secrets.APARAT_USERNAME }}
          APARAT_PASSWORD: ${{ secrets.APARAT_PASSWORD }}
        run: python upload_to_aparat.py
